config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :joggings
  get 'home/about'
  root 'joggings#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    if user.user?
      cannot :access, :rails_admin
    end

    if user.admin?
      can :manage, :all
    end

    if user.supervisor?
      can :manage, :all
      RailsAdmin.config do |config|
        config.model Jogging do
          visible false
        end
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jogging.rb
class Jogging < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :joggings
  
  enum role: [:admin, :user, :supervisor]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to "/", :notice => exception.message
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about 
  end
end

app/controllers/joggings_controller.rb
class JoggingsController < ApplicationController
  before_action :set_jogging, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show]
  

  # GET /joggings or /joggings.json
  def index
    @joggings = Jogging.all
  end

  # GET /joggings/1 or /joggings/1.json
  def show
  end

  # GET /joggings/new
  def new
    @jogging = Jogging.new
  end

  # GET /joggings/1/edit
  def edit
  end

  # POST /joggings or /joggings.json
  def create
    @jogging = Jogging.new(jogging_params)

    respond_to do |format|
      if @jogging.save
        format.html { redirect_to @jogging, notice: "Jogging was successfully created." }
        format.json { render :show, status: :created, location: @jogging }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @jogging.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /joggings/1 or /joggings/1.json
  def update
    respond_to do |format|
      if @jogging.update(jogging_params)
        format.html { redirect_to @jogging, notice: "Jogging was successfully updated." }
        format.json { render :show, status: :ok, location: @jogging }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @jogging.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /joggings/1 or /joggings/1.json
  def destroy
    @jogging.destroy
    # respond_to do |format|
    #   format.js { }
    #   format.html { redirect_to joggings_url, notice: "Jogging was successfully destroyed." }
    #   format.json { head :no_content }
    # end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jogging
      @jogging = Jogging.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def jogging_params
      params.require(:jogging).permit(:first_name, :last_name, :distance, :time, :date, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/joggings_helper.rb
module JoggingsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Jogging Tracker", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Add Result", new_jogging_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
              <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
              <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
              <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>
        <% end %>


      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/joggings/_chart_data.html.erb
<% data = {}%>
<% current_user.joggings.where("date(date) >= ? and date(date) <= ?",(Date.current-7).strftime("%Y-%m-%d"), Date.current.strftime("%Y-%m-%d")).map{ |jogging| data[jogging.date.strftime("%d / %m")] = jogging.distance } %>
<%= column_chart data,:library => {hAxis: {title: "X-label"}, vAxis: {title: "Y-label"}, title: "Graph title label"} %>

app/views/joggings/_form.html.erb
<%= form_with(model: jogging) do |form| %>
<% if jogging.errors.any? %>
<div id="error_explanation">
   <h2><%= pluralize(jogging.errors.count, "error") %> prohibited this jogging from being saved:</h2>
   <ul>
      <% jogging.errors.each do |error| %>
      <li><%= error.full_message %></li>
      <% end %>
   </ul>
</div>
<% end %>
<br/>
<div class="field form-group">
   <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
</div>
<br/>
<div class="field form-group">
   <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
</div>
<br/>
<div class="field form-group">
   <%= form.number_field :distance, class:"form-control", placeholder:"Distance", required: true %>
</div>
<br/>
<div class="field form-group">
   <%= form.number_field :time, class:"form-control", placeholder:"Time", required: true %>
</div>
<br />
<div class="field form-group">
   <%= form.date_field :date, class:"form-control", placeholder:"Date", required: true %>
</div>
<br />
<div class="field form-group">
   <%= form.number_field :user_id, id: :jogging_user_id, class:"form-control", value:current_user.id, type: :hidden %>
</div>
<br />
<div class="actions">
   <%= form.submit class:"btn btn-primary btn-lg btn-block" %>
</div>
<% end %>

app/views/joggings/destroy.js.erb
$("#chart-1").html("<%=escape_javascript(render 'chart_data') %>")
$("#jogging-<%=@jogging.id%>").remove();

app/views/joggings/edit.html.erb
<br />
<h1>Edit Jogging</h1>

<%= render 'form', jogging: @jogging %>

<br />
<%= link_to 'Show', @jogging, class:"btn btn-outline-dark" %>
<%= link_to 'Delete', @jogging, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-dark" %>
<%= link_to 'Back', joggings_path, class:"btn btn-outline-dark" %>

app/views/joggings/index.html.erb
<style>
  #chart-2{
    display:none;
  }
  #chart-3{
    display:none;
  }
  #chart-4{
    display:none;
  }
  #chart-5{
    display:none;
  }
  #chart-6{
    display:none;
  }
  #chart-7{
    display:none;
  }  
</style>

<br />
<table class="table table-hover">
  <thead class="table-dark">
    <tr>
      <th>Distance</th>
      <th>Time</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @joggings.each do |jogging| %>
    <% if jogging.user == current_user %>
      <tr id="jogging-<%=jogging.id%>">
        <td><%= jogging.distance %> meters </td>
        <td><%= jogging.time %> seconds</td>
        <td><%= jogging.date %></td>
        <td><%= link_to 'Show', jogging %></td>
        <td><%= link_to 'Edit', edit_jogging_path(jogging) %></td>
        <td><%= link_to 'Delete', jogging, method: :delete, data: { confirm: 'Are you sure?', remote: true } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New Result', new_jogging_path, class:"btn btn-outline-dark" %>

<br />

<div class="text-center">
  <h1>Last 7 Days Data</h1>
</div>
<%= render 'chart_data' %>

app/views/joggings/new.html.erb
<br />
<h1>Add Result</h1>
<br />

<%= render 'form', jogging: @jogging %>

<br />

<%= link_to 'Back', joggings_path, class:"btn btn-outline-dark" %>

app/views/joggings/show.html.erb
<br />
<div class="jumbotron">
    <h1 class="display-4">
        <%= @jogging.first_name %>
        <%= @jogging.last_name %>
    </h1>
    <hr class="my-4">
    <p class="lead">
        <strong> Distance: <b><%= @jogging.distance %> meters</b> </strong> &nbsp; •
        &nbsp; <strong> Time: <b><%= @jogging.time %> seconds</b> </strong> &nbsp; •
        &nbsp; <strong> Date: <b><%= @jogging.date %></b> </strong> &nbsp; •
        &nbsp; <strong> Average speed: <b><%= @jogging.distance / (@jogging.time.to_i == 0 ? 1 : @jogging.time.to_i) %> m/s</b></strong>
    </p>
    <br />
    <%= link_to 'Edit', edit_jogging_path(@jogging), class:"btn btn-outline-dark" %>
    <%= link_to 'Back', joggings_path, class:"btn btn-outline-dark" %> <br />
    <br />
    <% data = {}%>
    <% current_user.joggings.where("date(date) >= ? and date(date) <= ?",(Date.current-7).strftime("%Y-%m-%d"), Date.current.strftime("%Y-%m-%d")).map{ |jogging| data[jogging.date.strftime("%d / %m")] = (jogging.distance.to_i / (jogging.time.to_i == 0 ? 1 : jogging.time.to_i )) } %>
    <%= column_chart data,:library => {hAxis: {title: "X-label"}, vAxis: {title: "Y-label"}, title: "Graph title label"} %>
</div>

app/views/layouts/_alerts.html.erb
<br />
<div class="alert alert-secondary" role="alert">
    <%= notice %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    
    <title>Jogging Tracker</title>
  </head>
  <body>
    <%= render "home/header" %>
    <div class="container">
      <% if flash[:notice].present? %>
        <%= render "layouts/alerts" %>  
      <% end %>

      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
    -->
  </body>
</html>